# Generated by Django 5.0.6 on 2024-05-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employess',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
